apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-pod-team1-rs
  labels:
    app: team1-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team1
  template:
    metadata:
      name: my-pod-team1
      labels:
        app: team1
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
          - containerPort: 80
